### ISSUE TITLE
Broken search

### ISSUE THREAD

**Issue by mrPsycho** [Undev/redmine_tagging#68]
redmine 3.2-stable

```
Processing by SearchController#index as HTML
  Parameters: {"utf8"=>"✓", "wiki_pages"=>"1", "q"=>"google", "id"=>"lan"}
  Current user: y.n (id=13)
Completed 500 Internal Server Error in 13ms (ActiveRecord: 4.6ms)

ArgumentError (wrong number of arguments (1 for 0)):
  plugins/redmine_tagging/init.rb:29:in `block (2 levels) in <top (required)>'
  lib/plugins/acts_as_searchable/lib/acts_as_searchable.rb:186:in `call'
  lib/plugins/acts_as_searchable/lib/acts_as_searchable.rb:186:in `search_scope'
  lib/plugins/acts_as_searchable/lib/acts_as_searchable.rb:92:in `search_result_ranks_and_ids'
  lib/redmine/search.rb:127:in `block in load_result_ids'
  lib/redmine/search.rb:125:in `each'
  lib/redmine/search.rb:125:in `load_result_ids'
  lib/redmine/search.rb:115:in `block in load_result_ids_from_cache'
  lib/redmine/search.rb:114:in `load_result_ids_from_cache'
  lib/redmine/search.rb:99:in `result_ids'
  lib/redmine/search.rb:70:in `result_count'
  app/controllers/search_controller.rb:65:in `index'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

**Comment by mrPsycho** [comment]
https://github.com/Undev/redmine_tagging/pull/69 it fixes
